### ISSUE TITLE
检测出错，大佬麻烦看一眼是什么问题

### ISSUE THREAD

**Issue by skylover007** [youshandefeiyang/SSRSpeedN-Mod#2]
检测了一个节点，但是好像中间有什么错误，我该怎么解决。

首先我完全不懂编程什么的，python是什么更不知道。我的系统是windows 11 pro 韩文版，python装的是3.9.6，试过3.10.0也不行，因为是韩文系统，直接运行你的批处理文件“开始检测.bat”会全部乱码，所以参考了MacOS端的使用方法手动安装依赖和运行的，不知道对不对

麻烦你了，大佬，谢谢

![2021-11-12_133027](https://user-images.githubusercontent.com/35911123/141416528-5b8a0eed-b4cb-4cea-a45a-7958b566c25b.png)

![2021-11-12-13-28-41](https://user-images.githubusercontent.com/35911123/141416685-8c8693c9-e317-43b5-9f88-e709da83ca95.png)

![화면 캡처 2021-11-12 134359](https://user-images.githubusercontent.com/35911123/141416555-509f9c6a-6823-46e4-8044-c5ddc95ac793.png)

**Comment by skylover007** [comment]
再上传一个在python 3.10.0下的错误


![2021-11-12_143004](https://user-images.githubusercontent.com/35911123/141421138-b9e4f501-60ec-4cb4-9b11-cc3eaa1b5085.png)

**Comment by youshandefeiyang** [comment]
是你的这个节点不支持任何流媒体解锁，程序没有任何问题

**Comment by skylover007** [comment]
> 是你的这个节点不支持任何流媒体解锁，程序没有任何问题

![2021-11-12-12-08-58](https://user-images.githubusercontent.com/35911123/142097236-3a00b735-15b5-488c-a9bc-4a5dd91a523b.png)

不是吧，我测出过所有节点也是这样的。节点名上写着“原生IP”的节点确实是解锁了奈非所有节目的

**Comment by skylover007** [comment]
> 是你的这个节点不支持任何流媒体解锁，程序没有任何问题

不是吧，我测过所有节点都是这样的，节点上写着“原生IP”的确实是解锁了奈非当地所有节目（包括非自制）

![2021-11-12-12-08-58](https://user-images.githubusercontent.com/35911123/142101748-7dd0df5f-dbda-4a63-92ee-1147d72aefbb.png)
![화면 캡처 2021-11-17 102425](https://user-images.githubusercontent.com/35911123/142101994-b900bb85-8905-4a8a-935e-2595da07773f.png)

**Comment by skylover007** [comment]
我虽然不懂这些是什么意思，这里是不是不正常啊？

![QQ截图20211117102914](https://user-images.githubusercontent.com/35911123/142105080-6228c7b1-1902-4fbb-bd5c-556d1d991723.jpg)

**Comment by youshandefeiyang** [comment]
用非管理员模式检测

**Comment by skylover007** [comment]
> 用非管理员模式检测

没用管理员模式，还是一样的错误
