### ISSUE TITLE
建议ping不通的就不检测流媒体

### ISSUE THREAD

**Issue by Marcus0605** [youshandefeiyang/SSRSpeedN-Mod#4]
节点ping不通的话，还要检测流媒体的话会非常浪费时间的，建议开始ping不通就不检测流媒体了，直接标识一下跳过就好了，希望采纳或者提个能解决的办法哈

**Comment by youshandefeiyang** [comment]
这个项目不是我自己的，我只是魔改，ping只阉割剩下了googleping，可以去原项目进行反馈一下

**Comment by youshandefeiyang** [comment]
看看readme有原项目地址
