### ISSUE TITLE
迪士尼检测有瑕疵

### ISSUE THREAD

**Issue by a5582323** [youshandefeiyang/SSRSpeedN-Mod#6]
`r = requests.get("https://www.disneyplus.com/", proxies={
					"http": "socks5h://127.0.0.1:%d" % LOCAL_PORT,
					"https": "socks5h://127.0.0.1:%d" % LOCAL_PORT
				}, timeout=20, allow_redirects=False)

				if (r.status_code == 200):
					dtype = True
				else:
					dtype = False`
现在是只要能打开首页就算支持，实际上打开https://www.disneyplus.com/login登录页后经过验证，能输入账号登录才算支持

**Comment by youshandefeiyang** [comment]
去原项目提交一下issue
https://github.com/PauperZ/SSRSpeedN
